FROM golang:1.21

ENV DBUSER admin
ENV DBPASS back2books

# Set destination for COPY
WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./

# Build
RUN go build -o /back2books

EXPOSE 8080

# Run
CMD ["/back2books"]
