name: Build and deploy Go app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.4'  # Specify the Go version you want to use

      # - name: Install dependencies
      #   run: |
      #     go clean -modcache
      #     go get github.com/joelouie222/CS3773_back2books
      #     go install github.com/joelouie222/CS3773_back2books
      
      - name: Run go build
        run: |
          cd go
          go build -o b2b -x
      
      - name: Create artifact
        run: zip -r release.zip ./* r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: go-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: go-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'back2books'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_887C03BABDA4457C9E79540C75A563C2 }}
          package: .
